### ISSUE TITLE
Consider programmatic version updates.

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-apps-installer#1]
Versions are currently hardcoded at https://github.com/OSC/ood-apps-installer/blob/master/Rakefile#L5-L10

Consider using the [github releases API](
https://developer.github.com/v3/repos/releases/) to programmatically get the latest release tag from github and use that, with an optional parameter to specify another tag.

That way we don't need to keep updating the script when versions update.

**Comment by nickjer** [comment]
I am *slightly* against this as I'd like to keep each release of `ood-apps-installer` to a defined set of app versions. That way we know we have a set of apps that play well together.

**Comment by ericfranz** [comment]
We will not be doing this, since ood-apps-installer is now synced with OOD Release versions advertised in the OOD documentation and on the mailing list.
